<?php

namespace AppBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * TemperaturRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemperaturRepository extends EntityRepository
{
}
