<?php

namespace AppBundle\Repository;

/**
 * TemperaturRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemperaturRepository extends \Doctrine\ORM\EntityRepository
{
}
